name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        env:
          ENV: qa
          WORKERS: 2
          BASE_URL: ${{ secrets.BASE_URL }}
          QA_EMAIL: ${{ secrets.QA_EMAIL }}
          QA_PASSWORD: ${{ secrets.QA_PASSWORD }}
          QA_FIRST_NAME: ${{ secrets.QA_FIRST_NAME }}
          QA_LAST_NAME: ${{ secrets.QA_LAST_NAME }}
          QA_POSTAL_CODE: ${{ secrets.QA_POSTAL_CODE }}

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: reports/playwright/
          retention-days: 30

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-results
          path: allure-results/
          retention-days: 30
